//! Build script for omnect-os-init.
//!
//! Reads Yocto build-time environment variables and generates compile-time
//! constants into `$OUT_DIR/build_config.rs`, included via the `config::build`
//! module.
//!
//! All constants are `Option<u64>`:
//! - `None`  when the variable is absent (e.g. GRUB systems, local dev builds)
//! - `Some(n)` when Yocto provides the value
//!
//! Yocto variables → Rust constants:
//! | Env var                        | Constant          | Used by        |
//! |--------------------------------|-------------------|----------------|
//! | OMNECT_PART_OFFSET_UBOOT_ENV1  | UBOOT_ENV1_START  | flash-mode-1   |
//! | OMNECT_PART_OFFSET_UBOOT_ENV2  | UBOOT_ENV2_START  | flash-mode-1   |
//! | OMNECT_PART_SIZE_UBOOT_ENV     | UBOOT_ENV_SIZE    | flash-mode-1   |
//! | OMNECT_PART_SIZE_DATA          | DATA_SIZE         | flash-mode-1   |
//! | BOOTLOADER_SEEK                | BOOTLOADER_START  | flash-mode-1   |

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    check_feature_flags();

    // Tell Cargo to re-run this build script whenever any of these env vars change.
    println!("cargo:rerun-if-env-changed=OMNECT_PART_OFFSET_UBOOT_ENV1");
    println!("cargo:rerun-if-env-changed=OMNECT_PART_OFFSET_UBOOT_ENV2");
    println!("cargo:rerun-if-env-changed=OMNECT_PART_SIZE_UBOOT_ENV");
    println!("cargo:rerun-if-env-changed=OMNECT_PART_SIZE_DATA");
    println!("cargo:rerun-if-env-changed=BOOTLOADER_SEEK");

    let uboot_env1_start = read_u64_env("OMNECT_PART_OFFSET_UBOOT_ENV1");
    let uboot_env2_start = read_u64_env("OMNECT_PART_OFFSET_UBOOT_ENV2");
    let uboot_env_size = read_u64_env("OMNECT_PART_SIZE_UBOOT_ENV");
    let data_size = read_u64_env("OMNECT_PART_SIZE_DATA");
    let bootloader_start = read_u64_env("BOOTLOADER_SEEK");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let dest = out_dir.join("build_config.rs");

    let content = format!(
        "// Auto-generated by build.rs from Yocto environment variables. Do not edit.\n\
         \n\
         /// Start sector of the first U-Boot environment partition.\n\
         pub const UBOOT_ENV1_START: Option<u64> = {uboot_env1_start};\n\
         /// Start sector of the second U-Boot environment partition.\n\
         pub const UBOOT_ENV2_START: Option<u64> = {uboot_env2_start};\n\
         /// Size (in bytes) of the U-Boot environment.\n\
         pub const UBOOT_ENV_SIZE: Option<u64> = {uboot_env_size};\n\
         /// Initial size of the data partition (in KB).\n\
         pub const DATA_SIZE: Option<u64> = {data_size};\n\
         /// Start offset of the bootloader area (optional, platform-specific).\n\
         pub const BOOTLOADER_START: Option<u64> = {bootloader_start};\n",
        uboot_env1_start = fmt_option(uboot_env1_start),
        uboot_env2_start = fmt_option(uboot_env2_start),
        uboot_env_size = fmt_option(uboot_env_size),
        data_size = fmt_option(data_size),
        bootloader_start = fmt_option(bootloader_start),
    );

    fs::write(&dest, content).unwrap_or_else(|e| {
        panic!("Failed to write {}: {}", dest.display(), e);
    });
}

/// Reads an env var and parses it as `u64`. Returns `None` if absent or unparseable.
fn read_u64_env(var: &str) -> Option<u64> {
    env::var(var).ok().and_then(|v| {
        v.trim()
            .parse::<u64>()
            .map_err(|_| {
                println!(
                    "cargo:warning={var} value {:?} is not a valid u64, ignoring",
                    v
                );
            })
            .ok()
    })
}

fn fmt_option(val: Option<u64>) -> String {
    match val {
        Some(n) => format!("Some({n}_u64)"),
        None => "None".to_string(),
    }
}

/// Enforce mutually-exclusive feature combinations at build time.
///
/// Emitting `cargo:error=` here (rather than inline `compile_error!`) keeps
/// the validation in one place and avoids dead-code in the source tree.
fn check_feature_flags() {
    let has_grub = env::var("CARGO_FEATURE_GRUB").is_ok();
    let has_uboot = env::var("CARGO_FEATURE_UBOOT").is_ok();

    if has_grub && has_uboot {
        println!(
            "cargo:error=features `grub` and `uboot` are mutually exclusive; enable exactly one"
        );
    } else if !has_grub && !has_uboot {
        println!("cargo:error=exactly one of features `grub` or `uboot` must be enabled");
    }

    let has_gpt = env::var("CARGO_FEATURE_GPT").is_ok();
    let has_dos = env::var("CARGO_FEATURE_DOS").is_ok();

    if has_gpt && has_dos {
        println!("cargo:error=features `gpt` and `dos` are mutually exclusive; enable exactly one");
    } else if !has_gpt && !has_dos {
        println!("cargo:error=exactly one of features `gpt` or `dos` must be enabled");
    }
}
